version: '3.9'
services:
  mysql:
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: noventech
      MYSQL_ROOT_HOST: '%'
    image: mysql/mysql-server:8.0.23
    ports:
      - 3306:3306
    restart: always
    volumes:
      - mysql-8:/var/lib/mysql

  mssql:
    environment:
      SA_PASSWORD: "<Noventech1234!>"
      ACCEPT_EULA: "Y"
      # username is SA
    # image: mcr.microsoft.com/mssql/server:2017-latest
    image: mcr.microsoft.com/azure-sql-edge:latest
    ports:
      - "1433:1433"
    volumes:
      - mssql-17:/var/opt/mssql

  postgres:
    environment:
      POSTGRES_PASSWORD: noventech
    # image: postgres:9.5
    # image: postgres:10.9
    # image: postgres:11.6
    image: postgres:13.5
    ports:
      - 5432:5432
    volumes:
      # - postgres-9:/var/lib/postgresql/data/
      # - postgres-10:/var/lib/postgresql/data/
      # - postgres-11:/var/lib/postgresql/data/
      - postgres-13:/var/lib/postgresql/data

  rabbitmq:
    hostname: 'shared-rabbitmq'
    image: rabbitmq:3-management
    ports:
      - 15672:15672
      - 5672:5672
    restart: always
    volumes:
      - rabbitmq:/var/lib/rabbitmq/mnesia/
      - rabbitmq-logs:/var/log/rabbitmq/
      # - '~/.docker-conf/rabbitmq/data/:/var/lib/rabbitmq/mnesia/'
      # - '~/.docker-conf/rabbitmq/logs/:/var/log/rabbitmq/'

  redis:
    command: redis-server
    image: redis:5-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis:/data/

volumes:
  mssql-17:
  mysql-8:
  postgres-9:
  postgres-10:
  postgres-11:
  postgres-13:
  rabbitmq:
  rabbitmq-logs:
  redis:
